### ISSUE TITLE
Column for solutions in assignments page

### ISSUE THREAD

**Issue by kyeb** [revalo/lmodplus#1]
Some classes post solutions to exams or problem sets on the assignments page - this could possibly be shown on the assignments page of LMOD+ as a new column.

I looked briefly at the API, but don't quite have a good enough grasp on how the LMOD service works to do this myself rn

**Comment by revalo** [comment]
Thanks for the suggestion! I've added this, I think the commit (8c19233) is a pretty good representation of how new features can be added 😄
