### ISSUE TITLE
Differentiate between PDF, XML, and URL in Materials

### ISSUE THREAD

**Issue by cmnord** [revalo/lmodplus#3]
Old LMOD has SVG icons for each material type.
![image](https://user-images.githubusercontent.com/14882297/48518926-279a3e80-e839-11e8-9202-160e8648ea69.png)

Maybe LMOD+ could prefix each link with the text "[URL]" "[PDF]", or "[XML]"? https://github.com/revalo/lmodplus/blob/bc8a19bf16c7ec2379317dfa017fc9718d383aa4/src/html/main.html#L44

**Comment by revalo** [comment]
Thanks for the suggestion! 😊
This isn't enabled by default, but has been added as a setting under the new settings tab.


#### Screenshots:

![image](https://user-images.githubusercontent.com/5702827/48526075-4ce87600-e854-11e8-9c1d-f393bdfbe429.png)

![image](https://user-images.githubusercontent.com/5702827/48526089-583ba180-e854-11e8-90a8-27c7e23b6234.png)

**Comment by cmnord** [comment]
Thanks! This is super helpful for me :smile:

**Comment by cmnord** [comment]
Related question: do I need to do anything to see this change? I'm using the Firefox add-on.

**Comment by revalo** [comment]
So, I plan on doing releases every night that new stuff is added, and Firefox should update automatically every so often. Though, you can always just clone the repo and drag the folder into Firefox development mode add-on thingy 😛
