### ISSUE TITLE
LMOD Links Go to First Class in List

### ISSUE THREAD

**Issue by bancona** [revalo/lmodplus#7]
When I click on a link to a class LMOD page, like https://learning-modules.mit.edu/class/index.html?uuid=/course/6/sp19/6.006#dashboard, LMOD+ sends me to the first class on the list of classes I am taking, instead of to 6.006 in this case (unless it is the first on the list).

This would be nice for setting up bookmarks on my browser, so I can immediately go to the LMOD+ page for 6.006.

**Comment by revalo** [comment]
cc2ea62 should fix this! Thanks for the issues 😄
