### ISSUE TITLE
Missing File Types: PPT

### ISSUE THREAD

**Issue by hanryhu** [revalo/lmodplus#8]
Looks like an extension of Issue https://github.com/revalo/lmodplus/issues/3.  PPT are shown without icons in the Materials view.  Maybe they should have some kind of generic icon, if not an icon specific to the file type.

Screenshot comparisons below.
LMOD:
<img width="297" alt="Screen Shot 2019-11-02 at 5 01 12 PM" src="https://user-images.githubusercontent.com/38797540/68077004-a6fa8800-fd92-11e9-9087-1c0c306d519e.png">

LMOD+:
<img width="274" alt="Screen Shot 2019-11-02 at 4 59 47 PM" src="https://user-images.githubusercontent.com/38797540/68076995-82061500-fd92-11e9-82a7-f2f7bcdfcfb2.png">

**Comment by revalo** [comment]
Thanks for the issue! This has been added 😃
